services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: taylordex
      POSTGRES_USER: taylordex
      POSTGRES_PASSWORD: taylordex_secure_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://taylordex:taylordex_secure_pass@postgres:5432/taylordex
      - REDIS_URL=redis://redis:6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=taylordex
      - POSTGRES_USER=taylordex
      - POSTGRES_PASSWORD=taylordex_secure_pass
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=taylordex
      - DB_USER=taylordex
      - DB_PASSWORD=taylordex_secure_pass
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock:ro

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  default:
    name: taylordex_network
